version: '3'
services: 
#  webserver:
#    build: webserver/
#    ports:
#      - "80:80"
#    volumes:
#      - - ./sslcert:/sslcert
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:0.84.6
    volumes:
      - ./homeassistant/home-assistant-configuration:/config
      - /etc/localtime:/etc/localtime:ro
      - ./sslcert:/sslcert
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
  appdaemon:
    build: appdaemon/
    restart: always
    ports: 
      - "5050:5050"
    volumes:
      - ./appdaemon/home-assistant-apps/conf:/conf
      - ./appdaemon/home-assistant-apps/apps:/apps
      - ./appdaemon/home-assistant-apps/dashboards:/dashboards
