version: '3'
services: 
  webserver:
    build: webserver/
    ports:
      - "80:80"
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./homeassistant/home-assistant-configuration:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host